/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as openzeppelin from "./@openzeppelin";
export type { openzeppelin };
import type * as contracts from "./contracts";
export type { contracts };
export * as factories from "./factories";
export type { Ownable } from "./@openzeppelin/contracts/access/Ownable";
export { Ownable__factory } from "./factories/@openzeppelin/contracts/access/Ownable__factory";
export type { Bet } from "./contracts/Bet";
export { Bet__factory } from "./factories/contracts/Bet__factory";
export type { BetFactory } from "./contracts/BetFactory";
export { BetFactory__factory } from "./factories/contracts/BetFactory__factory";
export type { Lock } from "./contracts/Lock";
export { Lock__factory } from "./factories/contracts/Lock__factory";
