/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Bet } from "./Bet";
export type { BetFactory } from "./BetFactory";
export type { Lock } from "./Lock";
